spring:
  application:
    name: poker-mentor-webui
  
  datasource:
    url: jdbc:postgresql://localhost:5432/poker_mentor
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

  # Fallback to H2 if PostgreSQL is not available
  profiles:
    active: postgres

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.pokermentor: DEBUG
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
  
  h2:
    console:
      enabled: true
      path: /h2-console